server:
   port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 后期改成docker容器名
    url: jdbc:mysql://localhost:3306/my_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    # 后期改成docker容器名
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

minio:
  # 后期改成docker容器名
  endpoint: http://localhost:9000
  bucketName: myblog
  accessKey: minioadmin
  secretKey: minioadmin